spring:
  application:
    name:
      backend

  datasource:
    url: jdbc:mysql://192.168.100.232:3306/hotel_management
    username: cuongdso
    password: Pcuong@2411

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false